services:
  pizzapi:
    container_name: pizzapi-container
    build:
      context: ./pizzapi
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./pizzapi:/app
    develop:
      watch:
        - action: sync
          path: ./pizzapi
          target: /app
          ignore:
            - node_modules/

  pizzapp:
    container_name: pizzapp-container
    build:
      context: ./pizzapp
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./pizzapp:/app
     
    develop:
      watch:
        - action: sync
          path: ./pizzapp
          target: /app
          ignore:
            - node_modules/
            - .next/
