name: Cypress Tests

on:
  push:
    branches: [ "feature/cicd" ]  

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix: 
          browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browsers: ${{ matrix.browsers }}
          command: npx cypress run --browser  ${{ matrix.browsers }} --reporter-options reportDir=cypress/reports/${{ matrix.browsers }}
       
      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/${{ matrix.browsers }}/*.json > cypress/reports/${{ matrix.browsers }}/merged-reports.json

      - name: Generate HTML Reports
        run: npx marge cypress/reports/${{ matrix.browsers }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browsers }} -f "${{ matrix.browsers }}-report.html"

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
            name: Cypress HTML Report ${{ matrix.browsers }}
            path: cypress/reports/${{ matrix.browsers }}

      - name: Check Code Coverage
        run: |
          if [ ! -f "coverage/coverage-summary.json" ]; then
            echo "❌ Fichier de coverage non trouvé."
            exit 1
          fi
          
          coverage=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "📊 Code Coverage actuel: $coverage%"
          
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "❌ Code coverage insuffisant: $coverage% (minimum requis: 80%)"
            exit 1
          else
            echo "✅ Code coverage OK: $coverage% (≥ 80%)"
          fi

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
            name: Cypress HTML Report ${{ matrix.browsers }}
            path: cypress/reports/${{ matrix.browsers }}
